version: '3'
services:
  # api:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3333:3333"
  #   env_file:
  #     - ./backend/.env
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - '${POSTGRES_PORT_EXT:-5432}:5432'
    env_file:
      - .env
    # volumes:
    #   - ./volumes/pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    logging:
      driver: none
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    env_file:
      - .env
    #    volumes:
    #      - ./volumes/pgadmin/config:/var/lib/pgadmin
    ports:
      - '${PGADMIN_PORT_EXT:-8080}:80'
    restart: unless-stopped

  # admin:
  #   build:
  #     context: ./admin
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:80"
  #   container_name: admin-ui

  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:80"
  #   container_name: client-ui
